/**
 * @description authentication actions
 */
export const LOGIN_INPUT_CHANGE = "HANDLE_LOGIN_TEXT_INPUT";
export const SUBMITTING_LOGIN_CREDENTIALS = "IS_SUBMITTING_LOGIN_CREDENTIALS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/**
 * @description social authentication
 */
export const CANCEL_SOCIAL_AUTH = "CANCEL_SOCIAL_AUTH";
export const IS_OPENING_SOCIAL_AUTH_PROVIDER = "IS_OPEN_SOCIAL_AUTH_PROVIDER";
export const SUBMITTING_SOCIAL_AUTH = "SUBMITTING_SOCIAL_AUTH";
export const SETTING_TOKEN_SOCIAL_AUTH = "SETTING_TOKEN_SOCIAL_AUTH";
export const SOCIAL_AUTH_SUCCESS = "SOCIAL_AUTH_SUCCESS";
export const SOCIAL_AUTH_FAILED = "SOCIAL_AUTH_FAILED";
